// Light catalogue metadata ONLY — this module must never import from ./cards.
// The Library page and app shell import LIBRARY_CATEGORIES, so pulling in the
// heavy card content here would put the ~590 kB `card-data` chunk on the
// landing critical path. Phrase aggregation lives in ./phrases-data (loaded
// lazily by the routes/overlays that need it).

export type CardImpact = "high" | "medium" | "low";
export type CardDifficulty = "Easy" | "Easy-Medium" | "Medium" | "Hard";

interface LibraryCard {
  id: string;
  title: string;
  loaded: boolean;
  impact: CardImpact;
  // Mirrors CARD_DATA[id].overview.difficulty. Duplicated here (like impact) so
  // the Library can filter/sort without importing the heavy card content;
  // a content invariant keeps the two in sync.
  difficulty: CardDifficulty;
}

export const LIBRARY_CATEGORIES: Record<string, LibraryCard[]> = {
  "Voice / Presence": [
    {
      id: "TC028",
      title: "Warm vocal baseline",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC029",
      title: "Strategic silence",
      loaded: true,
      impact: "high",
      difficulty: "Medium",
    },
    {
      id: "TC031",
      title: "Slow down under pressure",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC035",
      title: "Strategic pause",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
  ],
  "Influence / Framing": [
    {
      id: "TC017",
      title: "Values-based framing",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC021",
      title: "Autonomy release",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC026",
      title: "Tactical mirroring",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC027",
      title: "Permission-based advice",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
  ],
  "Clarity / Direction": [
    {
      id: "TC011",
      title: "Summary check",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC012",
      title: "Full-attention signal",
      loaded: true,
      impact: "high",
      difficulty: "Easy",
    },
    {
      id: "TC013",
      title: "Clean request",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC014",
      title: "Validate the concern",
      loaded: true,
      impact: "high",
      difficulty: "Medium",
    },
    {
      id: "TC015",
      title: "Premature advice restraint",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC019",
      title: "Small ask",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC020",
      title: "Low-friction ask",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC034",
      title: "Two-option questions",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC042",
      title: "PREP",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC043",
      title: "OARS",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC044",
      title: "BLUF",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC045",
      title: "Ask-tell-ask",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC046",
      title: "Elicit-provide-elicit",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC047",
      title: "STAR",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC048",
      title: "SCQA",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC049",
      title: "CARL",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC050",
      title: "What? So what? Now what?",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC051",
      title: "RASA",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC052",
      title: "SBI",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC053",
      title: "NVC / OFNR",
      loaded: true,
      impact: "high",
      difficulty: "Hard",
    },
    {
      id: "TC066",
      title: "BIFF",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC068",
      title: "Specific ask",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC074",
      title: "DESC",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC080",
      title: "NURSE",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC081",
      title: "COIN",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC086",
      title: "LEAP",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC088",
      title: "One-screen message",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC094",
      title: "Bounded request",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC095",
      title: "DEAR MAN",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
  ],
  "Connection / Warmth": [
    {
      id: "TC001",
      title: "Live thread follow-ups",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC002",
      title: "Support response over shift response",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC003",
      title: "Comment-before-question",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC004",
      title: "Reflective listening",
      loaded: true,
      impact: "high",
      difficulty: "Medium",
    },
    {
      id: "TC005",
      title: "Validation without agreement",
      loaded: true,
      impact: "high",
      difficulty: "Hard",
    },
    {
      id: "TC006",
      title: "Emotional labelling",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC010",
      title: "Warm presence",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC016",
      title: "Active-constructive responding",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC018",
      title: "Specific appreciation",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC022",
      title: "Status generosity",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC023",
      title: "Loaded word follow-up",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC024",
      title: "Warm opening",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC025",
      title: "Exact word pickup",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC030",
      title: "Echo plus question",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC032",
      title: "Name and detail memory",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC033",
      title: "Minimal encouragers",
      loaded: true,
      impact: "low",
      difficulty: "Easy",
    },
    {
      id: "TC036",
      title: "Contextual opener",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC037",
      title: "Double-sided reflection",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC038",
      title: "Conversation threading",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC039",
      title: "Common-ground discovery",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC040",
      title: "Meaning reflection",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC041",
      title: "Topic energy tracking",
      loaded: true,
      impact: "low",
      difficulty: "Hard",
    },
    {
      id: "TC054",
      title: "Similarity signalling",
      loaded: true,
      impact: "low",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC056",
      title: "Topic preference detection",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC057",
      title: "Shared identity language",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC058",
      title: "Feeling-plus-need reflection",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC059",
      title: "Energy-based topic switching",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC060",
      title: "Positive assumption",
      loaded: true,
      impact: "high",
      difficulty: "Medium",
    },
    {
      id: "TC061",
      title: "Tone reflection",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC062",
      title: "Thread return",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC063",
      title: "Make them the expert",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC064",
      title: "Check before interpreting",
      loaded: true,
      impact: "high",
      difficulty: "Medium",
    },
    {
      id: "TC065",
      title: "Conversation bookmarking",
      loaded: true,
      impact: "low",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC067",
      title: "Advice request",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC070",
      title: "Careful normalising",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC071",
      title: "Conversation re-entry after interruption",
      loaded: true,
      impact: "low",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC072",
      title: "Low-pressure invitation",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC075",
      title: "Acknowledge effort",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC078",
      title: "Callback bridge",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC082",
      title: "Turn-toward bids",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC084",
      title: "Listen for values",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC087",
      title: "Story invitation",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC090",
      title: "Do-not-fix-yet discipline",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC093",
      title: "How-so prompt",
      loaded: true,
      impact: "high",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC096",
      title: "Capitalisation extension",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC098",
      title: "Emotion before facts",
      loaded: true,
      impact: "high",
      difficulty: "Medium",
    },
    {
      id: "TC100",
      title: "What-did-you-make-of-it question",
      loaded: true,
      impact: "medium",
      difficulty: "Easy-Medium",
    },
  ],
  "Resilience / Recovery": [
    {
      id: "TC007",
      title: "No one-upping discipline",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC008",
      title: "No-overexplaining discipline",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC009",
      title: "Anti-boomerasking discipline",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC069",
      title: "Clarify objection",
      loaded: true,
      impact: "high",
      difficulty: "Medium",
    },
    {
      id: "TC073",
      title: "Resistance-as-information",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC076",
      title: "Interrogation avoidance",
      loaded: true,
      impact: "low",
      difficulty: "Medium",
    },
    {
      id: "TC077",
      title: "Agreement before disagreement",
      loaded: true,
      impact: "high",
      difficulty: "Medium",
    },
    {
      id: "TC079",
      title: "Permission to disagree",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC083",
      title: "Ask what would make it workable",
      loaded: true,
      impact: "medium",
      difficulty: "Medium",
    },
    {
      id: "TC085",
      title: "Question-stacking restraint",
      loaded: true,
      impact: "low",
      difficulty: "Easy-Medium",
    },
    {
      id: "TC089",
      title: "Risk reduction",
      loaded: true,
      impact: "medium",
      difficulty: "Hard",
    },
    {
      id: "TC091",
      title: "Forced-humour restraint",
      loaded: true,
      impact: "low",
      difficulty: "Hard",
    },
    {
      id: "TC092",
      title: "Face-saving disagreement",
      loaded: true,
      impact: "high",
      difficulty: "Hard",
    },
    {
      id: "TC099",
      title: "Humblebrag avoidance",
      loaded: true,
      impact: "low",
      difficulty: "Easy-Medium",
    },
  ],
};
